build:
	gcc Compile_link_by_exec.c -o one
	gcc copy_files.c -o two
	gcc Line_word_count.c -o three
	gcc min_max_multithreading.c -lpthread  -o four
	gcc mini_shell.c -o five
	gcc signal_to_target.c -o six
	gcc time.c -lpthread -o seven